# As this is a single pod solution the scaling is linear, 
# each pod will have 1 user news and weather service, 1 news service
# and 1 weather service.
replicaCount: 1

apikeys:
  # The API key for NewsAPI.org
  newsApiKey: yourNewsAPIOrgKey
  # The API Key for OpenWeatherMap.org
  openWeatherApiKey: yourOpenWeatherMapKey

# This is the port the User News and Weather service will be visible on.
service:
  type: NodePort
  port: 32000

# Configure deployment in a service mesh
serviceMesh:
  istio: true

# These are the ports that the API Builder services run on in the pod.
# Should be no reason to change them.
ports:
  usernewsandweather: 18080
  news: 18081
  weather: 18082

# The images to use for the containers. If you built with different
# naming then you can change these here.
image:
  weather: axway/api-builder-demo-services:weather-service
  news: axway/api-builder-demo-services:news-service
  userNewsAndWeather: axway/api-builder-demo-services:user-news-and-weather
  pullPolicy: IfNotPresent

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - news-service.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

