{{if eq .Values.kubernetes.version "1.9.0"}}
apiVersion: apps/v1
{{ else }}
apiVersion: apps/v1beta2
{{end}}
kind: Deployment
metadata:
  name: {{ .Release.Name }}-news
  labels:
    app: news-service
    chart: {{ template "user-news-and-weather.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount.news }}
  selector:
    matchLabels:
      app: "news-service"
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: "news-service"
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: news
          image: "{{ .Values.image.news }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ARROW_NEWSAPI_APIKEY
              value: {{ .Values.apikeys.newsApiKey }}
            - name: ARROW_ISTIO_ENABLED
              value: "{{ .Values.serviceMesh.istio }}"
          livenessProbe:
            httpGet:
              path: /arrowPing.json
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          {{if eq .Values.serviceMesh.istio false}}
          readinessProbe:
            httpGet:
              path: /arrowPing.json
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          {{end}}
