apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-news
  labels:
    app: news-service
    chart: {{ template "user-news-and-weather.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http-news  
  selector:
    app: news-service
    release: {{ .Release.Name }}
