apiVersion: v1
kind: Service
metadata:
  name: {{ template "user-news-and-weather.fullname" . }}
  labels:
    app: {{ template "user-news-and-weather.name" . }}
    chart: {{ template "user-news-and-weather.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      nodePort: {{ .Values.service.port }}
  selector:
    app: {{ template "user-news-and-weather.name" . }}
    release: {{ .Release.Name }}
