apiVersion: v1
kind: Service
metadata:
  name: weather
  labels:
    app: {{ .Chart.Name }}-weather
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    apic-managed: "true"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Chart.Name }}-weather
    release: {{ .Release.Name }}
