apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-news-and-weather
  namespace: {{.Release.Namespace}}
  labels:
    app: {{ .Chart.Name }}-unw
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-unw
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-unw
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: usernewsandweather
          image: "{{ .Values.image.userNewsAndWeather }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              value: "{{ .Values.usernewsandweather.port }}"
            - name: NEWS_PORT
              value: "{{ .Values.news.port }}"
            - name: NEWS_SERVICE_APIKEY
              value: "{{ .Values.news.apikey }}"
            - name: WEATHER_PORT
              value: "{{ .Values.weather.port }}"
            - name: WEATHER_SERVICE_APIKEY
              value: "{{ .Values.weather.apikey }}"
            - name: APIKEY
              value: "{{ .Values.usernewsandweather.apikey }}"
          ports:
            - name: http
              containerPort: {{ .Values.usernewsandweather.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /apibuilderPing.json
              port: {{ .Values.usernewsandweather.port }}
          {{if eq .Values.serviceMesh.istio false}}
          readinessProbe:
            httpGet:
              path: /apibuilderPing.json
              port: {{ .Values.usernewsandweather.port }}
          {{end}}
        - name: news
          image: "{{ .Values.image.news }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              value: "{{ .Values.news.port }}"
            - name: APIKEY
              value: "{{ .Values.news.apikey }}"
            - name: NEWSAPI_APIKEY
              value: {{ .Values.news.backendKey }}
          livenessProbe:
            httpGet:
              path: /apibuilderPing.json
              port: {{ .Values.news.port }}
          {{if eq .Values.serviceMesh.istio false}}
          readinessProbe:
            httpGet:
              path: /apibuilderPing.json
              port: {{ .Values.news.port }}
          {{end}}
        - name: weather
          image: "{{ .Values.image.weather }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              value: "{{ .Values.weather.port }}"
            - name: APIKEY
              value: "{{ .Values.weather.apikey }}"
            - name: OPENWEATHER_APIKEY
              value: {{ .Values.weather.backendKey }}
          livenessProbe:
            httpGet:
              path: /apibuilderPing.json
              port: {{ .Values.weather.port }}
          {{if eq .Values.serviceMesh.istio false}}
          readinessProbe:
            httpGet:
              path: /apibuilderPing.json
              port: {{ .Values.weather.port }}
          {{end}}
