apiVersion: v1
kind: Service
metadata:
  name: user-news-and-weather
  labels:
    app: {{ .Chart.Name }}-unw
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.usernewsandweather.port }}
      targetPort: http
      protocol: TCP
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.port }}
      {{- end }}
      name: http
  selector:
    app: {{ .Chart.Name }}-unw
    release: {{ .Release.Name }}
