# Change this to scale the services by different amounts.
replicaCount:
  news: 1
  weather: 1
  info: 1
  
apikeys:
  # The API key for NewsAPI.org
  newsApiKey: 20064a29433f4d7e9f39da28763bc937
  # The API Key for OpenWeatherMap.org
  openWeatherApiKey: 9aff104318a1bd1674b1736f86cb7c6e

# This is the port the User News and Weather service will be visible on.
service:
  type: NodePort
  port: 32000

# The images to use for the containers. If you built with different
# naming then you can change these here.
image:
  weather: axway/api-builder-demo-services:weather-service
  news: axway/api-builder-demo-services:news-service
  userNewsAndWeather: axway/api-builder-demo-services:user-news-and-weather
  pullPolicy: IfNotPresent

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - news-service.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

